build: `placeos-2.2411.0` (#302)

diff --git a/.github/workflows/update-openapi-docs.yml b/.github/workflows/update-openapi-docs.yml
--- a/.github/workflows/update-openapi-docs.yml
+++ b/.github/workflows/update-openapi-docs.yml
@@ -1,11 +1,9 @@
 name: Update Open API Docs
 
 on:
-  workflow_dispatch:
-    inputs:
-      version:
-        description: 'Version to be updated in versions.json'
-        required: true
+  push:
+    branches:
+      - release
 
 jobs:
   update-open-api-doc-links:
@@ -15,41 +13,51 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
-            submodules: true
+          submodules: true
+          token: ${{ secrets.REPO_ACCESS_TOKEN }}
 
       - name: Configure git user
         run: |
-          git config user.email "robots@place.technology"
-          git config user.name "PlaceOS Robot"
+          git config --global user.email "robots@place.technology"
+          git config --global user.name "PlaceOS Robot"
+
+      - name: Retrieve Version
+        id: get_version
+        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
 
       - name: Update OPEN API Doc Links
         shell: bash
+        env:
+          VERSION: ${{ env.VERSION }}
         run: |
-          git fetch --all
+          set -e  # Exit if any command fails
 
           submodules=("services/rest-api" "services/staff-api")
 
           for submodule in "${submodules[@]}"; do
-            commit_id=$(git submodule status "$submodule" | awk '{print $1}')
+            cd "$submodule"
+            git fetch
+            commit_id=$(git rev-parse HEAD)
             module_name=$(basename "$submodule")
-            new_url="https://raw.githubusercontent.com/PlaceOS/${module_name}/${commit_id}/OPENAPI_DOC.yml"
+            cd - > /dev/null
 
-            input_file="swagger/$module_name/versions.json"
+            cd "swagger/$module_name"
+            git checkout master
+            git pull origin master
+
+            new_url="https://raw.githubusercontent.com/PlaceOS/${module_name}/${commit_id}/OPENAPI_DOC.yml"
+            input_file="versions.json"
             temp_file=$(mktemp)
 
-            jq --arg version "${{ github.event.inputs.version }}" --arg new_url "$new_url" \
+            jq --arg version "$VERSION" --arg new_url "$new_url" \
               'to_entries | (.[0:1] + [{"key": $version, "value": $new_url}] + .[1:]) | from_entries' \
               "$input_file" > "$temp_file"
 
             mv "$temp_file" "$input_file"
-          done
-          pushd swagger
-          for dir in */; do
-            cd "$dir"
-            git add versions.json
-            git commit -m "build: update for ${{ github.event.inputs.version }}"
-            git push origin
-            cd ..
-          done
-          popd
 
+            git add versions.json
+            git commit -m "build: update for $VERSION"
+            git push origin master
+
+            cd ../../
+          done
